export { default as About } from './About';
export { default as Apps } from './Apps';
export { default as Handmade } from './Handmade';
export { default as Home } from './Home';
export { default as Resume } from './Resume';
export { default as UX } from './UX';
export { default as ProjectWeb } from './ProjectWeb';
export { default as ProjectHand } from './ProjectHand';
export { default as ProjectUX } from './ProjectUX';